### ISSUE TITLE
Convert project to TypeScript

### ISSUE THREAD

**Issue by themakshter** [OpenVentPk/ventilator-app#1]
TypeScript is a superset of JavaScript and helps developers write less erroneous code as it provides compile time type-checking etc.

The initial version of the application was written in plain JS for speed but we should look into converting the project into a TypeScript one.

**Comment by danishkarim** [comment]
I think this issue should be closed too.

**Comment by themakshter** [comment]
There is still work to be done in improving typescript errors, but that can be considered a separate task. Closing.
