### ISSUE TITLE
Overflow alarm metric displays properly on alarms tab

### ISSUE THREAD

**Issue by themakshter** [OpenVentPk/ventilator-app#14]
The current display of alarm metrics does not overflow onto the next line for some reason. We have set up the `wrap` setting via flex but it does not respect. It allows up to 9 on the same line before throwing up rendering issues. So this needs looking into/fixing.

**Comment by themakshter** [comment]
Ideally, we want to just keep adding as many panels and have it overflow, but if that doesn't work for any reason, we can just manually create two rows for a tablet display.

**Comment by aqilusman45** [comment]
Hi, please review. Thanks
