### ISSUE TITLE
Create main monitoring view

### ISSUE THREAD

**Issue by themakshter** [OpenVentPk/ventilator-app#16]
This will be the default screen viewed by the users. It will be showing the following parameters and their values:

1. Peak Pressure
2. Peep
3. FiO2
4. Plateau Pressure
5. BPM
6. I:E Ratio
7. Tidal Volume
8. Ventilator Mode
9. Breathing mode
10. Flow Rate

This page will also show the following graphs:

- Pressure
- Volume
- Flow

- If any of the metrics breach the limits set for them, they should display the value in red to denote alarm.

Sample screen from TV-100 Simulation
![image](https://user-images.githubusercontent.com/2033876/80892949-0e53af00-8cc6-11ea-8103-2f119ea79bf9.png)

**Comment by danishkarim** [comment]
Should we close this issue, the main screen is done. only bug fixes remain

**Comment by themakshter** [comment]
Agreed. This is also completed.
