### ISSUE TITLE
Match theme to specs

### ISSUE THREAD

**Issue by themakshter** [OpenVentPk/ventilator-app#2]
This is the image provided to use by @1Umair7:

![image](https://user-images.githubusercontent.com/2033876/80314077-0dfb7580-87e7-11ea-8430-c524b1bc0574.png)

We want to update the style to match as close as possible

**Comment by themakshter** [comment]
We were able to find the actual source of this - thanks the @AftabSaraz.

https://ugobyte.wixsite.com/home/ui - this is the person who designed it and we also have a simulation accessible at https://biomeddeviceslms.com/tv-100-simulation/ (username and password are both `biomedtv100`).

We can play around with it and I feel most interactions will be quite similar to that interface so we can use it as a base.

**Comment by danishkarim** [comment]
This issue should be closed too, they settled for a different theme.

**Comment by themakshter** [comment]
Yeah, that makes sense. I'll create an issue regarding the new task of consolidating themes.

**Comment by themakshter** [comment]
Closing as we moved to use a separate theme.
